#!/usr/bin/env python3
"""Generate standalone adapters from the shared tutor specification."""
from pathlib import Path
import argparse
import sys
ROOT = Path(__file__).resolve().parents[1]
def outputs():
    body = (ROOT / "spec/ai-tutor.md").read_text().strip() + "\n"
    version = (ROOT / "VERSION").read_text().strip()
    marker = f"<!-- Generated by scripts/build.py; version {version}; edit spec/ai-tutor.md. -->\n\n"
    skill = "---\nname: ai-tutor\ndescription: AI家庭教師としてコード・PR・設計・技術テーマを具体例とミニ実践で学ぶ。AI家庭教師の依頼やレビューで確認する観点の抽出を依頼されたときに使う。\n---\n\n"
    copilot = "---\nname: ai-tutor\ndescription: コードやPRを教材に教えるAI家庭教師。レビュー支援モードにも対応。\nagent: ask\n---\n\n"
    web = "# AI家庭教師：チャット初期設定\n\nこの全文を新しいチャットで一度送信する。登録だけでは授業を始めず、登録した旨を短く返す。普段の役割を維持し、ユーザーが「AI家庭教師」と依頼したときだけ以下を適用する。終了後は通常の会話へ戻る。\n\n"
    return {
        "skills/ai-tutor/SKILL.md": skill + marker + body,
        "prompts/copilot/ai-tutor.prompt.md": copilot + marker + "指定された教材についてAI家庭教師を開始する。レビュー支援の指定があればそのモードを使う。\n\n" + body,
        "prompts/web/ai-tutor.webui.md": web + marker + body,
    }
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    bad = []
    for name, value in outputs().items():
        p = ROOT / name
        if args.check:
            if not p.exists() or p.read_text() != value: bad.append(name)
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(value)
    if bad:
        print("Generated files differ: " + ", ".join(bad), file=sys.stderr)
        return 1
    print("Generated adapters are consistent." if args.check else "Generated adapters.")
    return 0
if __name__ == "__main__":
    raise SystemExit(main())
